### PR TITLE
Ll edits

### PR DESCRIPTION
**Pull request by Leasw144**
Hey guys, please look over the code CAREFULLY as there were a lot of cosmetic changes done. In particular, some percentages were converted to ems as I felt they were somewhat more standardized but we can discuss this as a group next we meet and change them as necessary.

Other changes included adding a title-display for our h2 element outside of the form box and also one added to the 'start activity' button to get it to go right.

Everything else is cosmetic- but still need to add color. Let me know what you think!
Screen Shot 2020-05-27 at 11 52 49 PM

### CODE REVIEW

**Review by JWoltjen — COMMENTED** [review]
I like the re-organization here!

**Review by JWoltjen — COMMENTED** [review]
Looks like we've added another class to specifically target "New Activities", works for me.

**Review by JWoltjen — COMMENTED** [review]
I approve changing the border of the right section to white. Now for the text!

**Review by JWoltjen — COMMENTED** [review]
Logical to me. Approved.

**Review by JWoltjen — COMMENTED** [review]
It looks like you've used grid to solve our second line button problem. I'm impressed! Can you walk me through this the next time we meet? Awesome work!

**Comment by JWoltjen** [comment]
I approve of all these changes. Steph, if it passes your review as well, go ahead and merge the pull request.

**Comment by StephLSohns** [comment]
Linus, such good work, thank you so much. The span around button was exactly what we needed for that and also really like what you did with names - naming conventions needed to be improved going forward as well as cleaning up the code for greater order of css selectors but also neatness for developer friendly code - thank you for all of your work, it might be an indicator of how we need to move forward - divide and conquer might be a more solid way to go.

**Review by StephLSohns — COMMENTED** [review]
Solid work followed by better naming conventions and strong cleanup.

**Pull request merged**
